# ✍️ Description:
# This is a composite action, which means it can be used in other actions.
# It is used in almost all workflows to set up the environment and install dependencies.
# Updating  the package manager or Node version here will be reflected in all workflows.

name: 'Setup Node & Install dependencies'
description: 'Setup Node environment with PNPM and Dependencies'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'

    - name: 📦 Install Project Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash